name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  smoke:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -e '.[dev]'
      - run: black --check .
      - run: ruff .
      - run: pyright mutants2 --level error
      - run: vulture mutants2
      - run: pytest -q tests/smoke --cov=mutants2 --cov-report=term

  full:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -e '.[dev]'
      - run: black --check .
      - run: ruff .
      - run: pyright mutants2 --level error
      - run: vulture mutants2
      - run: pytest -q --cov=mutants2 --cov-report=term --cov-fail-under=85
